### PR TITLE
Added script to make C$ function work. 

### PR DESCRIPTION
**Pull request by belibug**
Added one function, Launch C$ explorer works for both single as well as multi device input.

### CODE REVIEW

**Comment by belibug** [comment]
Hey @nkasco , I just created one function to get hang of the process. Suggest if it needs any modification. Once you are fine I can start adding other scripts fairly quickly.

**Comment by nkasco** [comment]
It'll make readability a bit better if we use this at the top of each script instead of `$args`
`param(
        $Machine
)`

**Comment by belibug** [comment]
Agreed, Let's call it ` param ( $machines ) ` so that we can handle multiple machines as well. 

You can deny this pull request. I will create a branch on this repo directly and raise pull request again.

**Comment by nkasco** [comment]
I think you should just be able to update your current branch and push, no?

**Comment by belibug** [comment]
This is updated, can you check now.

**Review by nkasco — APPROVED** [review]

**Pull request merged**
